/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafebyndt;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author niraj
 */
public class cafendt extends javax.swing.JFrame {
double [] drink = new double [5];
double [] cake = new double [8];
double [] cost = new double [3];
double [] i = new double[10];
 
    /**
     * Creates new form cafendt
     */
    public cafendt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        ckbcocake = new javax.swing.JCheckBox();
        ckbrvcake = new javax.swing.JCheckBox();
        ckbbccake = new javax.swing.JCheckBox();
        ckbbfcake = new javax.swing.JCheckBox();
        ckbocake = new javax.swing.JCheckBox();
        ckbcccake = new javax.swing.JCheckBox();
        ckbvcake = new javax.swing.JCheckBox();
        ckbbcake = new javax.swing.JCheckBox();
        cocake = new javax.swing.JTextField();
        rvcake = new javax.swing.JTextField();
        bccake = new javax.swing.JTextField();
        bfcake = new javax.swing.JTextField();
        ocake = new javax.swing.JTextField();
        cccake = new javax.swing.JTextField();
        vcake = new javax.swing.JTextField();
        bcake = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        costcake = new javax.swing.JTextField();
        costdrink = new javax.swing.JTextField();
        costcharge = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        ckbcappu = new javax.swing.JCheckBox();
        ckbicappu = new javax.swing.JCheckBox();
        ckbespresso = new javax.swing.JCheckBox();
        ckblattle = new javax.swing.JCheckBox();
        ckbilattle = new javax.swing.JCheckBox();
        cappu = new javax.swing.JTextField();
        icappu = new javax.swing.JTextField();
        espresso = new javax.swing.JTextField();
        ilattle = new javax.swing.JTextField();
        lattle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(1362, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setForeground(new java.awt.Color(255, 102, 255));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 62)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Ndt's Cafe Systems");

        jLabel2.setFont(new java.awt.Font("Webdings", 0, 70)); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1330, 110));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Tax");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Sub Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Total");

        tax.setBackground(receipt.getBackground());
        tax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tax.setText("0");
        tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        subtotal.setBackground(receipt.getBackground());
        subtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subtotal.setText("0");
        subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        total.setBackground(receipt.getBackground());
        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("0");
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(subtotal))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 390, 200));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, 370, 90));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        receipt.setBackground(new java.awt.Color(255, 255, 153));
        receipt.setColumns(20);
        receipt.setRows(5);
        jScrollPane1.setViewportView(receipt);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Name:");

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Address:");

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("PRINT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addComponent(name)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(43, 43, 43))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 340, 440));

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        ckbcocake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbcocake.setText("coffe cake");
        ckbcocake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbcocakeMouseClicked(evt);
            }
        });

        ckbrvcake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbrvcake.setText("red velvet cake");
        ckbrvcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbrvcakeMouseClicked(evt);
            }
        });

        ckbbccake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbbccake.setText("boston cream pie");
        ckbbccake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbbccakeMouseClicked(evt);
            }
        });

        ckbbfcake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbbfcake.setText("black forrest cake");
        ckbbfcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbbfcakeMouseClicked(evt);
            }
        });

        ckbocake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbocake.setText("orange cake");
        ckbocake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbocakeMouseClicked(evt);
            }
        });

        ckbcccake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbcccake.setText("choco-chip cake ");
        ckbcccake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbcccakeMouseClicked(evt);
            }
        });

        ckbvcake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbvcake.setText("venila cake");
        ckbvcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbvcakeMouseClicked(evt);
            }
        });

        ckbbcake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbbcake.setText("banana cake");
        ckbbcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbbcakeMouseClicked(evt);
            }
        });

        cocake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cocake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cocake.setText("0");
        cocake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        cocake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocakeActionPerformed(evt);
            }
        });

        rvcake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rvcake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rvcake.setText("0");
        rvcake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        rvcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rvcakeActionPerformed(evt);
            }
        });

        bccake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bccake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bccake.setText("0");
        bccake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        bfcake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bfcake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bfcake.setText("0");
        bfcake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ocake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ocake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ocake.setText("0");
        ocake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        cccake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cccake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cccake.setText("0");
        cccake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        vcake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vcake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vcake.setText("0");
        vcake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        bcake.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bcake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bcake.setText("0");
        bcake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbcocake)
                    .addComponent(ckbrvcake)
                    .addComponent(ckbbccake)
                    .addComponent(ckbbfcake)
                    .addComponent(ckbocake)
                    .addComponent(ckbcccake)
                    .addComponent(ckbvcake)
                    .addComponent(ckbbcake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cocake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rvcake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bccake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bfcake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cccake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vcake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ckbcocake, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cocake, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbrvcake)
                    .addComponent(rvcake, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbbccake)
                    .addComponent(bccake, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbbfcake)
                    .addComponent(bfcake, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbocake)
                    .addComponent(ocake, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbcccake)
                    .addComponent(cccake, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbvcake)
                    .addComponent(vcake, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ckbbcake)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(bcake))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 400, 340));

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Cost Of Drinks");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Cost Of Cakes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Service Charge");

        costcake.setBackground(receipt.getBackground());
        costcake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        costcake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        costcake.setText("0");
        costcake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        costdrink.setBackground(receipt.getBackground());
        costdrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        costdrink.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        costdrink.setText("0");
        costdrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        costcharge.setBackground(receipt.getBackground());
        costcharge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        costcharge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        costcharge.setText("34.5");
        costcharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costcake, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costdrink, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(costdrink, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(costcake, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(costcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 550, 220));

        jPanel8.setBackground(new java.awt.Color(255, 153, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        ckbcappu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ckbcappu.setText("Cappuccino");
        ckbcappu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbcappuMouseClicked(evt);
            }
        });
        ckbcappu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbcappuActionPerformed(evt);
            }
        });

        ckbicappu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ckbicappu.setText("Ice Cappuccino");
        ckbicappu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbicappuMouseClicked(evt);
            }
        });
        ckbicappu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbicappuActionPerformed(evt);
            }
        });

        ckbespresso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ckbespresso.setText("Espresso");
        ckbespresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbespressoMouseClicked(evt);
            }
        });
        ckbespresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbespressoActionPerformed(evt);
            }
        });

        ckblattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ckblattle.setText("Lattle");
        ckblattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckblattleMouseClicked(evt);
            }
        });
        ckblattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckblattleActionPerformed(evt);
            }
        });

        ckbilattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ckbilattle.setText("Iced Lattle");
        ckbilattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbilattleMouseClicked(evt);
            }
        });
        ckbilattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbilattleActionPerformed(evt);
            }
        });

        cappu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cappu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cappu.setText("0");
        cappu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        cappu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cappuMouseClicked(evt);
            }
        });
        cappu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuActionPerformed(evt);
            }
        });

        icappu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        icappu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        icappu.setText("0");
        icappu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        espresso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        espresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        espresso.setText("0");
        espresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        ilattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ilattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ilattle.setText("0");
        ilattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        lattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lattle.setText("0");
        lattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbespresso)
                            .addComponent(ckblattle)
                            .addComponent(ckbilattle)
                            .addComponent(ckbcappu))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ckbicappu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cappu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icappu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espresso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lattle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilattle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbcappu)
                    .addComponent(cappu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icappu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbicappu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbespresso)
                    .addComponent(espresso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckblattle)
                    .addComponent(lattle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbilattle)
                    .addComponent(ilattle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 550, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rvcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rvcakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rvcakeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      costdrink.setText("0");
      costcake.setText("0");
      costcharge.setText("0");
      tax.setText("0");
      subtotal.setText("0");
      total.setText("0");
      cappu.setText("0");
      icappu.setText("0");
      espresso.setText("0");
      lattle.setText("0");
      receipt.setText(null);
      ilattle.setText("0");
      cocake.setText("0");
      rvcake.setText("0");
      bccake.setText("0");
      bfcake.setText("0");
      ocake.setText("0");
      cccake.setText("0");
      vcake.setText("0");
      bcake.setText("0");
      ckbcappu.setSelected(false);
      ckbicappu.setSelected(false);
      ckbespresso.setSelected(false);
      ckblattle.setSelected(false);
      ckbilattle.setSelected(false);
      ckbcocake.setSelected(false);
      ckbrvcake.setSelected(false);
      ckbbccake.setSelected(false);
      ckbbfcake.setSelected(false);
      ckbocake.setSelected(false);
      ckbcccake.setSelected(false);
      ckbvcake.setSelected(false);
      ckbbcake.setSelected(false);
      name.setText("");
      address.setText("");
      
      
              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cappuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cappuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       drink [0] = Double.parseDouble(cappu.getText());
       drink [1] = Double.parseDouble(icappu.getText());
       drink [2] = Double.parseDouble(espresso.getText());
       drink [3] = Double.parseDouble(lattle.getText());
       drink [4] = Double.parseDouble(ilattle.getText());
       cake [0] = Double.parseDouble(cocake.getText());
       cake [1] = Double.parseDouble(rvcake.getText());
       cake [2] = Double.parseDouble(bccake.getText());
       cake [3] = Double.parseDouble(bfcake.getText());
       cake [4] = Double.parseDouble(ocake.getText());
       cake [5] = Double.parseDouble(cccake.getText());
       cake [6] = Double.parseDouble(vcake.getText());
       cake [7] = Double.parseDouble(bcake.getText());
       cost[0] =Double.parseDouble(tax.getText());
       cost[1] =Double.parseDouble(subtotal.getText());
       cost[2] =Double.parseDouble(total.getText());
       
       String names = name.getText();
       String add = address.getText();
      
       int refs = 1325 + (int) (Math.random()*4238);
       //int ref = (refs);
       
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:MM:SS");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd:MMM:YYYY");
        Tdate.format(timer.getTime());
        
       
       
       
       
       receipt.append("\t\n\tNdt's cafe System:\n\n"+
       "Reference Number:\t" + refs +
       "\n==================================\t" +
               "\nName:\t\t" + names + "\nAddress:\t\t" + add +
       "\ncappuccino:\t\t"+ drink [0] +
       "\nice cappuccino:\t\t"+ drink [1] +
       "\nespresso:\t\t"+ drink [2] +
       "\nlattle:\t\t"+ drink [3] +
       "\nice lattle:\t\t"+ drink [4] +
               "\n==================================\t\t"+
               "\ncoffee:\t\t" + cake[0] +
               "\nred velvet:\t\t" + cake[1] +
               "\nboston creem:\t\t" + cake[2] +
               "\nblack forrest:\t\t" + cake[3] +
               "\norange:\t\t" + cake[4] +
               "\ncho-co chip:\t\t" + cake[5] +
               "\nvenila:\t\t" + cake[6] +
               "\nbanana:\t\t" + cake[7] +
               "\n==================================\t" +
               "\nTax:\t\t" + cost[0] + 
               "\nSub Total:\t\t" + cost[1] + 
               "\nTotal:\t\t" + cost[2] + 
               "\n==================================\t" +                
               "\nDate: " + Tdate.format(timer.getTime()) +
               "\tTime: " + tTime.format(timer.getTime()) +
        "\n\n\tThank You,Come Back\n");
    
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ckblattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckblattleActionPerformed
        
    }//GEN-LAST:event_ckblattleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      drink [0] = Double.parseDouble(costdrink.getText());
       drink [1] = Double.parseDouble(costcake.getText());
       drink [2] = Double.parseDouble(costcharge.getText());
      double ctotle = (drink[0]+drink[1]+drink[2]);
      String itaxtotle = String.format(" %.2f",ctotle/100);
      double subtotle =(ctotle);
     String isubtotle =String.format("%.2f",subtotle);
     double alltotle = (ctotle);
     String itotle;
     itotle = String.format("%.2f",alltotle + (alltotle/100));
      if(drink [0] == 0 && drink [1] == 0)
      {
          tax.setText("0");
     subtotal.setText("0");
     total.setText("0");
          
      }
      else
      {
     tax.setText(itaxtotle);
     subtotal.setText(isubtotle);
     total.setText(itotle);
      }
      
     
     
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ckbilattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbilattleActionPerformed
        
    }//GEN-LAST:event_ckbilattleActionPerformed

    private void ckbcappuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbcappuActionPerformed
        
    }//GEN-LAST:event_ckbcappuActionPerformed

    private void ckbicappuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbicappuActionPerformed
        
    }//GEN-LAST:event_ckbicappuActionPerformed

    private void ckbcappuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbcappuMouseClicked
        double ccapp = Double.parseDouble(costdrink.getText());
        double capp = Double.parseDouble(cappu.getText());
        double icapp = 89;
        
        if(ckbcappu.isSelected())
        {
            i[2]= (capp * icapp) + ccapp; 
            String pdrink = String.format("%.2f",i[2]);
            costdrink.setText(pdrink);
            //cappu.setText(pdrink);
        }
    }//GEN-LAST:event_ckbcappuMouseClicked

    private void ckbicappuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbicappuMouseClicked
        double cicapp = Double.parseDouble(costdrink.getText());
        double icapp = Double.parseDouble(icappu.getText());
        double iicapp = 109;
        
        if(ckbcappu.isSelected())
        {
            i[3]= (icapp * iicapp) + cicapp; 
            String pdrink = String.format("%.2f",i[3]);
            costdrink.setText(pdrink);
            //icappu.setText(pdrink);
        }
    }//GEN-LAST:event_ckbicappuMouseClicked

    private void ckbilattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbilattleMouseClicked
        double cilatt = Double.parseDouble(costdrink.getText());
        double ilatt = Double.parseDouble(ilattle.getText());
        double iilatt = 112;
        
        if(ckbilattle.isSelected())
        {
            i[1]= (ilatt * iilatt) + cilatt; 
            String pdrink = String.format("%.2f",i[1]);
            costdrink.setText(pdrink);
            //ilattle.setText(pdrink);
        }
    }//GEN-LAST:event_ckbilattleMouseClicked

    private void ckblattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckblattleMouseClicked
        double clatt = Double.parseDouble(costdrink.getText());
        double latt = Double.parseDouble(lattle.getText());
        double ilatt = 99;
        
        if(ckblattle.isSelected())
        {
            i[0]= (latt * ilatt) + clatt; 
            String pdrink = String.format("%.2f",i[0]);
            costdrink.setText(pdrink);
            //lattle.setText(pdrink);
        }
    }//GEN-LAST:event_ckblattleMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void ckbespressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbespressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbespressoActionPerformed

    private void ckbespressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbespressoMouseClicked
        // TODO add your handling code here:
        double cespresso = Double.parseDouble(costdrink.getText());
        double esoresso = Double.parseDouble(espresso.getText());
        double iespresso = 84;
        
        if(ckbespresso.isSelected())
        {
            i[4]= (esoresso * iespresso) + cespresso; 
            String pdrink = String.format("%.2f",i[4]);
            costdrink.setText(pdrink);
            //cappu.setText(pdrink);
        }
    }//GEN-LAST:event_ckbespressoMouseClicked

    private void ckbcocakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbcocakeMouseClicked
        // TODO add your handling code here:
        double ccocake = Double.parseDouble(costcake.getText());
        double cocak = Double.parseDouble(cocake.getText());
        double icocake = 300;
        
        if(ckbcocake.isSelected())
        {
            i[0]= (cocak * icocake) + ccocake; 
            String pcake = String.format("%.2f",i[0]);
            costcake.setText(pcake);
            
        }
    }//GEN-LAST:event_ckbcocakeMouseClicked

    private void cocakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cocakeActionPerformed

    private void ckbrvcakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbrvcakeMouseClicked
       double crvcake = Double.parseDouble(costcake.getText());
        double rvcak = Double.parseDouble(rvcake.getText());
        double irvcake = 300;
        
        if(ckbrvcake.isSelected())
        {
            i[1]= (rvcak * irvcake) + crvcake; 
            String pcake = String.format("%.2f",i[1]);
            costcake.setText(pcake);
            
        }
    }//GEN-LAST:event_ckbrvcakeMouseClicked

    private void ckbbccakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbbccakeMouseClicked
      double cbccake = Double.parseDouble(costcake.getText());
        double bccak = Double.parseDouble(bccake.getText());
        double ibccake = 300;
        
        if(ckbcocake.isSelected())
        {
            i[2]= (bccak * ibccake) + cbccake; 
            String pcake = String.format("%.2f",i[2]);
            costcake.setText(pcake);
            
        }  
    }//GEN-LAST:event_ckbbccakeMouseClicked

    private void ckbbfcakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbbfcakeMouseClicked
         double cbfcake = Double.parseDouble(costcake.getText());
        double bfcak = Double.parseDouble(bfcake.getText());
        double ibfcake = 300;
        
        if(ckbbfcake.isSelected())
        {
            i[3]= (bfcak * ibfcake) + cbfcake; 
            String pcake = String.format("%.2f",i[3]);
            costcake.setText(pcake);
            
        }
    }//GEN-LAST:event_ckbbfcakeMouseClicked

    private void ckbocakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbocakeMouseClicked
        double cocake = Double.parseDouble(costcake.getText());
        double ocak = Double.parseDouble(ocake.getText());
        double iocake = 300;
        
        if(ckbocake.isSelected())
        {
            i[4]= (ocak * iocake) + cocake; 
            String pcake = String.format("%.2f",i[4]);
            costcake.setText(pcake);
            
        } // TODO add your handling code here:
    }//GEN-LAST:event_ckbocakeMouseClicked

    private void ckbcccakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbcccakeMouseClicked
 double ccccake = Double.parseDouble(costcake.getText());
        double cccak = Double.parseDouble(cccake.getText());
        double icccake = 300;
        
        if(ckbcccake.isSelected())
        {
            i[5]= (cccak * icccake) + ccccake; 
            String pcake = String.format("%.2f",i[5]);
            costcake.setText(pcake);
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ckbcccakeMouseClicked

    private void ckbvcakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbvcakeMouseClicked
 double cvcake = Double.parseDouble(costcake.getText());
        double vcak = Double.parseDouble(vcake.getText());
        double ivcake = 300;
        
        if(ckbvcake.isSelected())
        {
            i[6]= (vcak * ivcake) + cvcake; 
            String pcake = String.format("%.2f",i[6]);
            costcake.setText(pcake);
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ckbvcakeMouseClicked

    private void ckbbcakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbbcakeMouseClicked
 double cbcake = Double.parseDouble(costcake.getText());
        double bcak = Double.parseDouble(bcake.getText());
        double ibcake = 300;
        
        if(ckbbcake.isSelected())
        {
            i[7]= (bcak * ibcake) + cbcake; 
            String pcake = String.format("%.2f",i[7]);
            costcake.setText(pcake);
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ckbbcakeMouseClicked

    private void cappuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cappuMouseClicked
        cappu.setText(null);
    }//GEN-LAST:event_cappuMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
        boolean complete = receipt.print();
        if(complete)
        {
            JOptionPane.showMessageDialog(null, "Done printing ..!1","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Printing..!!","Printer ",JOptionPane.ERROR_MESSAGE);
        }
    } catch (PrinterException ex) {
        Logger.getLogger(cafendt.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cafendt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cafendt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cafendt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cafendt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cafendt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField bcake;
    private javax.swing.JTextField bccake;
    private javax.swing.JTextField bfcake;
    private javax.swing.JTextField cappu;
    private javax.swing.JTextField cccake;
    private javax.swing.JCheckBox ckbbcake;
    private javax.swing.JCheckBox ckbbccake;
    private javax.swing.JCheckBox ckbbfcake;
    private javax.swing.JCheckBox ckbcappu;
    private javax.swing.JCheckBox ckbcccake;
    private javax.swing.JCheckBox ckbcocake;
    private javax.swing.JCheckBox ckbespresso;
    private javax.swing.JCheckBox ckbicappu;
    private javax.swing.JCheckBox ckbilattle;
    private javax.swing.JCheckBox ckblattle;
    private javax.swing.JCheckBox ckbocake;
    private javax.swing.JCheckBox ckbrvcake;
    private javax.swing.JCheckBox ckbvcake;
    private javax.swing.JTextField cocake;
    private javax.swing.JTextField costcake;
    private javax.swing.JTextField costcharge;
    private javax.swing.JTextField costdrink;
    private javax.swing.JTextField espresso;
    private javax.swing.JTextField icappu;
    private javax.swing.JTextField ilattle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lattle;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ocake;
    private javax.swing.JTextArea receipt;
    private javax.swing.JTextField rvcake;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField total;
    private javax.swing.JTextField vcake;
    // End of variables declaration//GEN-END:variables
}
